---
- name: Add bastion to group
  add_host:
    name: "bastion.{{ public_hosted_zone }}"
    groups: bastion
    openshift_node_labels:
      role: bastion
  when:
    - hostvars[item]['ec2_tag_aws_cloudformation_stack-name'] == "{{ stack_name }}"
    - byo_bastion == "no"
  with_items: "{{ groups['tag_openshift-role_bastion'] }}"

- name: Add masters to requisite groups
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: masters, etcd, nodes, cluster_hosts
    openshift_node_labels:
      role: master
  with_items: "{{ groups['tag_openshift-role_master'] }}"
  when:
    - hostvars[item]['ec2_tag_aws_cloudformation_stack-name'] == "{{ stack_name }}"

- name: Add a master to the primary masters group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: primary_master
    openshift_node_labels:
      role: master
  with_items: "{{ groups['tag_openshift-role_master'].0 }}"
  when:
    - hostvars[item]['ec2_tag_aws_cloudformation_stack-name'] == "{{ stack_name }}"

- name: Add infra instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: infra
  with_items: "{{ groups['tag_openshift-role_infra'] }}"
  when:
    - hostvars[item]['ec2_tag_aws_cloudformation_stack-name'] == "{{ stack_name }}"

- name: Add app instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: app
  with_items: "{{ groups['tag_openshift-role_app'] }}"
  when:
    - hostvars[item]['ec2_tag_aws_cloudformation_stack-name'] == "{{ stack_name }}"
